title: Xiaoran Zhang
profile: /assets/img/selfie_formal.jpg
description: University of California, Los Angeles
google_scholar: Idre5UgAAAAJ&hl=en
linkedin: Voldemort108X
github: xiaoran-笑然-zhang-171ba7170
resume: /assets/file/Xiaoran Zhang CV-2-paged - (Latest).pdf
theme: jekyll-theme-minimal
